### PR TITLE
Speed-up look-up operation

### PR DESCRIPTION
**Pull request by martinrohbeck**
This change speeds-up the lookup if the dataset has a large numer of samples.

For 350'000 samples and 100 features the time is reduced from approx 30mins to 1s. 

```Pyhton
from mudata import MuData
import numpy as np
import pandas as pd

# Create random data
N = 350000
G = 110
X = np.random.rand(N, G)
obs = pd.DataFrame({'cell_type': np.random.choice(['A', 'B', 'C'], N)})
var = pd.DataFrame({'gene': [f'gene_{i}' for i in range(G)]})
adata = sc.AnnData(X=X, obs=obs, var=var)
mdata = MuData({"test": adata})
mdata

model = cellij.FactorModel(n_factors=10)
model.add_data(mdata)
```

### CODE REVIEW

**Comment by martinrohbeck** [comment]
Tests are failing because the codecov cannot be run

**Review by timtreis — CHANGES_REQUESTED** [review]
Maybe add a comment stating that from there on the order is random, just in case we have a weird bug at one point. Can be merged then

**Comment by martinrohbeck** [comment]
> Maybe add a comment stating that from there on the order is random, just in case we have a weird bug at one point. Can be merged then

But the sets are used nowhere else?

**Comment by timtreis** [comment]
*not yet ☝️

**Comment by timtreis** [comment]
Wasted a day debugging a month ago on something that probably started like this, so I have PTSD for this set-shuffling now 😅

**Pull request merged**
